### ISSUE TITLE
show_fields.py returns error(s)

### ISSUE THREAD

**Issue by rambleondad** [tableau/document-api-python#130]
when I run: python show_fields.py, I get the following:

C:\Python\Tabdocumentapi\document-api-python-development>(cd "samples/show-field
s" && python show_fields.py)
Traceback (most recent call last):
  File "show_fields.py", line 9, in <module>
    sourceTDS = Datasource.from_file('world.tds')
  File "C:\Python\lib\site-packages\tableaudocumentapi\datasource.py", line 145,
 in from_file
    dsxml = xml_open(filename, 'datasource').getroot()
  File "C:\Python\lib\site-packages\tableaudocumentapi\xfile.py", line 32, in xm
l_open
    tree = ET.parse(filename)
  File "C:\Python\lib\xml\etree\ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "C:\Python\lib\xml\etree\ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, colum
n 2

Any ideas why?

thanks

**Comment by RussTheAerialist** [comment]
based on the error message, and that you are on windows, I think it's because `world.tds` is a symlink, which windows doesn't support.  Try making a copy of the real file from the `list-tds-info` directory into the `show-fields` directory

**Comment by rambleondad** [comment]
worked!  I copied/replaced the world.tds file in the show-fields directory and the show_fields.py works now!  thanks!

**Comment by RussTheAerialist** [comment]
👍
