### ISSUE TITLE
Cannot update port values of workbooks or datasources through document API

### ISSUE THREAD

**Issue by grbritz** [tableau/document-api-python#132]
When attempting to programmatically update the connection info for my workbook to repoint it to a different database, I ran into errors because the port # was not being updated to the new value. I can provide a workbook and/or datasource to use to repro this on request.

The below repro steps assume a workbook with one embedded data source containing one connection to a database (e.g. MySQL). I am trying to repoint the connection to the production replica which is stored on an Oracle database server and is served at a different port.

Repro steps:
```
import tableaudocumentapi as TDA
wb = TDA.Workbook(path_to_workbook)
wb.datasources[0].connections[0].dbclass = "oracle"
wb.datasources[0].connections[0].port = "1521"
wb.datasources[0].connections[0].server = "oracleserver.prod.domain"
wb.save()
```

The `dbclass` and `server` fields will update as expected on save, but the port # will remain unchanged.

**Comment by eandres-comextic** [comment]
wb.datasources[0].connections[0].server = "oracleserver.prod.domain,1521"
