### ISSUE TITLE
Support for migrating between site

### ISSUE THREAD

**Issue by JeffJames1** [tableau/document-api-python#136]
Provide to ability to change the site of a server data source embedded in a workbook. 

In the OEM space, we move content between sites all the time. The database connection switch works fine for locally defined data sources. Now, we need an "official" method of changing server data source targets.

**Comment by jacalata** [comment]
This is one scenario that the Content Migration Tool is built for - https://help.tableau.com/current/server/en-us/cmt-intro.htm. I'm going to assume that it meets your needs, but if it doesn't, that tool is officially supported so you can contact support to ask for help.
