### ISSUE TITLE
Tabcmd publish with .twb created via Document API

### ISSUE THREAD

**Issue by jgoffin** [tableau/document-api-python#14]
I can successfully create a .twb file via the Document API, but attempting to publish it to my Tableau Server via Tabcmd results in an unexpected error:

**Bad request
unexpected error occurred opening the packaged workbook.**

Attached is the template workbook created in Tableau Desktop (superstore_sales.twb) and one of the workbooks created from that template via the Document API (superstore_sales_arizona.twb)

[superstore_twbs.zip](https://github.com/tableau/document-api-python/files/285303/superstore_twbs.zip)

**Comment by t8y8** [comment]
It opens in Desktop for me, haven't reproduced with tabcmd yet.

Question, if you add <?xml version='1.0' encoding='utf-8' ?> to the top of the twb and save, does it work then?

**Comment by jgoffin** [comment]
Yep, adding <?xml version='1.0' encoding='utf-8' ?> fixed it!

**Comment by t8y8** [comment]
Did the TWB have the XML root before it went through the document api? I can't see a good reason why it would be stripped, but I'll need to dig in.

**Comment by t8y8** [comment]
Ok, the write method for elementtree has an xml_declaration parameter that we can set to True to include in all files written out -- but I want to make sure Desktop and Server both understand it.
