### ISSUE TITLE
'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by doulam** [tableau/document-api-python#145]
The API failed to parse fields from some twbx files with the following error.

'NoneType' object has no attribute 'text'

**Comment by t8y8** [comment]
Can you supply the twbx that generates the error? (Or a copy of the stack trace?)

**Comment by t8y8** [comment]
Update, I bet it's because the following `find` returns `None`:

```
            self._apply_attribute(xmldata, field_name, lambda x: xmldata.find('.//{}'.format(metadata_name)).text,
```
We'd really appreciate the TWB/TDS if possible so we can figure out what cases don't return a result.

**Comment by chris-aplin** [comment]
I hit this issue as well (version 9.3) and in my case the problematic columns seem to be SQL server columns of datetimeoffset in the datasource.  These have metadata-records without local-name or local-type which is what is causing the exception. Presumably this is because tableau does not actually enable this data for user selection but still keeps a record of that columns existence in the remote table. 

This really should be addressed because datetimeoffset is a common type in SQL server. Essentially all of my organization's workbooks with a SQL server connection are not compatible with the API since more or less every table has some metatdata columns of type datetimeoffset.

**Comment by t8y8** [comment]
@chris-aplin are you able to provide a twb with the issue? (This will make the fix much easier to test/futureproof).

If you aren't, thank you for the deep dive and info you provided, it will definitely help!

**Comment by swm4** [comment]
Running into the same issue as well on a version 10.5 workbook. Based on the stack trace, @t8y8 nailed the source line down (field.py line 65) but I don't know what I can do to get around it. Would a small twb file and stack trace be helpful for the development team? If so, let me know where to send the files. I'm loving this API and anxious to use it.

**Comment by t8y8** [comment]
@swm4 that would be exactly what we need, thank you!

**Comment by swm4** [comment]
@t8y8 What's the best way to get the files to you? I can open a Support ticket and attach the files or if you prefer a different method, let me know.

**Comment by t8y8** [comment]
If they're small enough you can attach them here, upload them to dropbox, etc -- if you'd rather not share that information publicly you can email me a link to them at tdoyle@tableau.com

**Comment by t8y8** [comment]
Working with @swm4 I was able to locate the issue.

His TWB has this column in it:
```
<metadata-record class='column'>
  <remote-name>SPAM</remote-name>
  <remote-type>1</remote-type>
  <remote-alias>SPAM</remote-alias>
  <ordinal>19</ordinal>
  <aggregation>Count</aggregation>
  <contains-null>true</contains-null>
  <attributes>
    <attribute datatype='string' name='DebugRemoteType'>&quot;xml&quot;</attribute>
    <attribute datatype='string' name='DebugWireType'>&quot;SQL_C_DEFAULT&quot;</attribute>
  </attributes>
</metadata-record>
```

That has no `local-type` tag.

When iterating through the `_METADATA_TO_FIELD_MAP` it looks for that tag, fails, and returns a `None` which of course has no `.text` attribute.

@RussTheAerialist is more familiar with the field parsing code than I am, I think we may be able to just assume a default type or just set it to `None`

**Comment by RussTheAerialist** [comment]
yeah sorry for the delay, I'm out of the office today, so I'll take a look at a more complete solution tomorrow.

**Comment by swm4** [comment]
@t8y8 That code seems to work for me. Thanks for your help. If you end up developing a different solution, I'm happy to test it out on other workbooks for you.

**Comment by ElPincheTopo** [comment]
@t8y8 @RussTheAerialist 
I have also been having the same issue since end of 2018, any chance this could be fixed?

**Comment by jacalata** [comment]
It looks like Russ fixed this in October 2021 with https://github.com/tableau/document-api-python/commit/805957e028b58a70c8289b1d556350dc8b97f7e0
