### ISSUE TITLE
Is 2018.X supported?

### ISSUE THREAD

**Issue by til-jmac** [tableau/document-api-python#153]
Less of an issue and more of a question really, but didn't know where best to ask it - your documentation states that 9.X and 10.X content is supported, am I correct in thinking 2018.X is supported too, or is it too early to say for sure?

**Comment by philshem** [comment]
I'm not official, and I didn't do extensive testing, but the API worked OK for my 2018.2 workbook

**Comment by koszti** [comment]
I asked it on the tableau conf 2 days ago and they said 2018.X is supported and _should_ work. However based on the fact what "_should_" means in real life I would test it first :)

**Comment by jacalata** [comment]
README updates will soon say it supports '20xx.x' documents as well.
