### ISSUE TITLE
Documentation: naming of datasource object

### ISSUE THREAD

**Issue by philshem** [tableau/document-api-python#156]
[Docs](http://tableau.github.io/document-api-python/docs/)   show multiple examples with the object:

    sourceWB.datasources     

According to `print(sourceWB.__dict__)`, the object is actually prefixed with an underscore

    sourceWB._datasources

**Comment by jacalata** [comment]
sourceWb._datasources does exist, but you shouldn't be using it.  It is common practice when coding in python to use an underscore to start the name as a sign that you should pretend the thing is private. You should instead use the setter, sourceWb.datasources, as shown in the docs.

For reference, here is a random blog article that explains the use this pattern of a setter with 'hidden' variable: https://www.programiz.com/python-programming/property
