### ISSUE TITLE
Does a copy workbook planned?

### ISSUE THREAD

**Issue by Amitg1** [tableau/document-api-python#161]
Hi, 

I'm willing to create a dashboard and then copy it and change the datasource, table and columns names.
is it possible?

if not, what's the blocker?

Thanks!

**Comment by jacalata** [comment]
I think this would be best achieved through our Content Migration Tool, although there are some limitations on which datasource connections it can handle. https://help.tableau.com/current/server/en-us/cmt-getting-started.htm. If you have specific questions about how to use this, the best place is probably the [Tableau Community Forum](https://community.tableau.com/s/global-search/%40uri#q=tableau%20content%20migration%20tool&t=All).
