### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by til-jmac** [tableau/document-api-python#168]
This project seems pretty dead to me - is anyone still looking at this? Is there another solution for modifying Tableau files as part of an automated promotion workflow (Test --> Prod) or are we stuck with this? I gather the new Server Management Add-on includes some tools that do this, but you have to pay for that...

**Comment by adrianturcato-initiative** [comment]
Seems like might be a good candidate for a community takeover?

**Comment by jacalata** [comment]
For 'reasons', it is just barely alive. It will have some more eyes on it now.
