### ISSUE TITLE
Updating workbook connection

### ISSUE THREAD

**Issue by arunyadav19** [tableau/document-api-python#184]
Hi,
Can I ask for some help here ?
I want to update server name in connection information in multiple workbooks.
Some of my workbooks have multiple data sources. My REST API based script is not working as expected, in some workbooks which have multiple data sources, it's not able to update the server name.
I heard that document API can do this stuff. Can someone help me with a working solution ?
I'm really stuck with my rest api script.

**Comment by ismailsimsek** [comment]
@arunyadav19 following code shuld work, for updating workbook connections
https://github.com/memiiso/pytableau/blob/8bc0e14cd1a9d136b175c2526aa237ad60dddd64/pytableau/__init__.py#L631
