### ISSUE TITLE
Set Actions lost after running Python Script

### ISSUE THREAD

**Issue by wesmott** [tableau/document-api-python#193]
Please see word attachment for detailed explanation.

[Set Action Issue.zip](https://github.com/tableau/document-api-python/files/6103136/Set.Action.Issue.zip)
[Set Action Issue.docx](https://github.com/tableau/document-api-python/files/6103143/Set.Action.Issue.docx)

**Comment by jacalata** [comment]
This will be fixed along with #162 with #196
