### ISSUE TITLE
Disabling Extract Through Python Tableau API

### ISSUE THREAD

**Issue by wesmott** [tableau/document-api-python#195]
Hello,

Has anybody found a way to disable an extract through the Python Tableau API?  I can't figure it out.  Would greatly appreciate any tip.  Thanks

**Comment by jacalata** [comment]
It sounds like you're asking how to stop an extract from being refreshed on Tableau Server? You would use TSC (https://tableau.github.io/server-client-python/) for that, or the underlying REST API for content management.

**Comment by jacalata** [comment]
closing because I see you're asking in the tsc repo
