### ISSUE TITLE
Validation at the document level and at the "Tableau" level

### ISSUE THREAD

**Issue by benlower** [tableau/document-api-python#20]
(copied from [developer forum post](https://community.tableau.com/thread/206900))

Validate that the document is correct (valid XML) and matches the known format of the Tableau document for that target product version, then validate that the document in terms of acceptable Tableau content (are the data connection class types valid, do the columns added to the rows/columns shelves actually present in the datasource, etc.). In other words, both syntactic and semantic validation.

**Comment by jacalata** [comment]
This is a long way beyond any current plans for this tool.
