### ISSUE TITLE
Support for Packaged Files

### ISSUE THREAD

**Issue by benlower** [tableau/document-api-python#22]
(copied from [developer forum post](https://community.tableau.com/thread/206900))

I realize that unpacking/repacking a TWBX is trivial, but it's also boilerplate stuff we have to do in every solution unless it becomes core capability.

**Comment by t8y8** [comment]
My current PR #13 has a stab at this -- I can rebase it on HEAD and add tdsx support

**Comment by t8y8** [comment]
This should be closed with #44 for twbx and tdsx
