### ISSUE TITLE
Additional Loggers added in the latest release while creating Workbook object

### ISSUE THREAD

**Issue by mohitbhandari37** [tableau/document-api-python#236]
Additional Loggers are added in the latest release while creating Workbook object, below is the output which lib generates while creating an object of Workbook class.

file_path=path of workbook file
wbObj=Workbook(file_path)

```
local-name id
local-type datatype
remote-alias alias
```

Kindly look in to the issue.

Thanks,
Mohit

**Comment by bcantoni** [comment]
@mohitbhandari37 we just fixed this in #238.

Let's leave this issue open until the next release and then we'll close it.

**Comment by dev-mkc19** [comment]
@bcantoni when will new release be? Why it takes so long time to fix this small bug?

**Comment by bcantoni** [comment]
@mohitbhandari37 @dev-mkc19 this fix should be available in release 0.11 from this morning. Thanks for the reminder nudge. Releases on this project happen infrequently.
