### ISSUE TITLE
Build-A-Sheet Workshop

### ISSUE THREAD

**Issue by benlower** [tableau/document-api-python#24]
(copied from [developer forum post](https://community.tableau.com/thread/206900))

Another use case for the Document API is the creation of new worksheets and dashboard programmatically. This has actually been done before for and by Tableau customers but not widely publicized in the community. I could envision a fluent API for sheet creation.

I'd love to be able to do like that Voyager project thing (Data Voyager) and turn a TDS into a TWB by creating all the vizzes that made sense for the dataset. This would mean a lot of "XML hacking," though, even with the aforementioned SDK. It'd be great if we could say "sheet.setDatasource(xyzDatasource).onColumns('some dimension').onColumns('some measure', 'running_sum').onRows('some dimension).asBarChart();" or similar.

**Comment by romainr** [comment]
+1 Creating a new view would be amazing.

**Comment by MrTomWhite** [comment]
@benlower I'm not convinced that a deeply nested fluent api is pythonic / the right design choice here.
The accepted commenter here has a few good points, which I'll quote verbatim. 
https://stackoverflow.com/questions/3883907/designing-an-python-api-fluent-interface-or-arguments

> 1.   dot-chaining makes for poor code-intellisense since the empirical prototype is just an empty Panel() or Bar(), you can of course pydoc on it, but in this day and age intellisense is available in most IDEs and a great productivity booster.
>
  > 2.  Chaining makes programatically calling the class much more difficult. It's very nice to be able to pass in a list or dict as *args, **kwargs -- while possible with chaining you'd basically have to support both methods or a bunch of backflips to meta-create the class.
>
> 3.   Chaining makes code more difficult to read because inevitably someone will do it all on one line, and wonder why things are all goofed up when they've passed in the same param twice -- you can prevent that but with a named param constructor dup filtering is basically built in.

I'm having a hard time remembering any parts of the standard library that use fluent api's. But maybe that could guide the design.

**Comment by jacalata** [comment]
out of scope
