### ISSUE TITLE
Update Project Organization 

### ISSUE THREAD

**Issue by t8y8** [tableau/document-api-python#3]
I think we should take another look at how the code is currently organized and see if we can't implement a few suggestions from the community (http://docs.python-guide.org/en/latest/writing/structure/#structure-of-the-repository is a great guide).

Off the top of my head, things I found odd:
- There was no tests file or folder (But I added one :) )
- Document API is a high level folder that I think can un-exist, so that setup.py is at the top level of the git repo
- tableaudocumentapi should be tableau-document-api for readability
- Do we want a different file per class for each of the models?
-- An alternative might be to have them all in a models.py file, or at least group them into a models subpackage so it becomes 'from models.connection import Connection' etc.
- Examples aren't runnable from a git clone -- you have to install first, it'd be nice if we moved the structure around so that we could just run them... we could do sys.path manipulation (ugly, but works), or something similar

Thoughts?

**Comment by benlower** [comment]
@t8y8 is the only remaining issue here that examples don't run from a clone? I'd prefer to keep them clean from any of the sys.path stuff if possible. would you feel better if we put this into pypi so that ppl could pip install?

**Comment by t8y8** [comment]
I think it's fine, the pip install -e works, as would pypi when it makes
its way there.

The final nit would be to make examples lowercase because then everything
is consistent :P

On Friday, May 27, 2016, Ben Lower <notifications@github.com> wrote:

> @t8y8 <https://github.com/t8y8> is the only remaining issue here that
> examples don't run from a clone? I'd prefer to keep them clean from any of
> the sys.path stuff if possible. would you feel better if we put this into
> pypi so that ppl could pip install?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tableau/document-api-python/issues/3#issuecomment-222229041>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEKwZWtv7zfYgkTFM4qtuiyTRn3PKsj3ks5qF0CogaJpZM4IbmtQ>
> .
>


-- 
--
Tyler Doyle
206.552.8451

**Comment by t8y8** [comment]
I'm happy closing this out :)
