### ISSUE TITLE
Enable connection class retargeting

### ISSUE THREAD

**Issue by benlower** [tableau/document-api-python#34]
Take an existing TDS file ( say  for  PostgreSQL DB )  and  change connection to MySQL/SQLServer/etc DB connection by changing the connection attributes from (class='postgres'  to class='mysql'  ) , Servername, dbname, port, username, auth-mode, sslmode, schema, single-node, workgroup-auth-mode.

**Comment by t8y8** [comment]
If we decide to allow this, it's just a matter of making the class attribute settable (Currently it's read only)

**Comment by t8y8** [comment]
I'm going to consider this closed by #65 and we can do new issue reports for the odd-ball attributes that specific connectors have
