### ISSUE TITLE
PR Merge Squashing

### ISSUE THREAD

**Issue by t8y8** [tableau/document-api-python#49]
https://help.github.com/articles/configuring-pull-request-merge-squashing/

Is this something we want to do for the document-api repo?

To accomplish this I was getting feedback on PRs until they were done, and then squashing and resubmitting in a new PR, but this seems like a much cleaner way to keep the discussion in one place?

**Comment by RussTheAerialist** [comment]
There is a dropdown when merging that you can pick between normal merge and squash merge.  I've just been using the squash merge option, but we should make it a default.  I don't think there is anything bad about it.

**Comment by t8y8** [comment]
Cool, I think @benlower has to switch the default since he owns the repo

**Comment by RussTheAerialist** [comment]
I think he already did, but I'll let him close the issue if he did.

**Comment by benlower** [comment]
"Allow merge commits" and "Allow squash merging" both enabled.
