### ISSUE TITLE
KeyError throwing when opening workbook

### ISSUE THREAD

**Issue by t8y8** [tableau/document-api-python#58]
Happens in the latest commit on the development branch
```
Traceback (most recent call last):
  File "party.py", line 4, in <module>
    wb = Workbook('Contact Us Form - Tasks.twbx')
  File "/Users/tdoyle/Documents/py/envs/party/lib/python3.5/site-packages/tableaudocumentapi/workbook.py", line 49, in __init__
    self._workbookRoot, self._datasource_index
  File "/Users/tdoyle/Documents/py/envs/party/lib/python3.5/site-packages/tableaudocumentapi/workbook.py", line 148, in _prepare_worksheets
    datasource.fields[column_name].add_used_in(worksheet_name)
  File "/Users/tdoyle/Documents/py/envs/party/lib/python3.5/site-packages/tableaudocumentapi/multilookup_dict.py", line 66, in __getitem__
    return dict.__getitem__(self, key)
KeyError: '[Account]'
```
Sending workbook via email since it's internal and I can't just toss it to GH :)

**Comment by benlower** [comment]
are you getting this error on other workbooks, or just this one in particular?

**Comment by t8y8** [comment]
I wrote a script to run through 73 workbooks I happened to have downloaded:

```
23 out of 73 workboks were opened successfully
0.3150684931506849%
```

@RussTheAerialist and I are chatting about it on hipchat, suspect it's another xml lookup issue of some sort

**Comment by RussTheAerialist** [comment]
Part of these failures are because the file version is 8.0.  Not all of them, so this is still a bug that needs to be tracked down, but we need to decide on what are support will be for older versions of the file format.

Also, nitpick, it's 31.5068...%, not 0.315068...%

**Comment by RussTheAerialist** [comment]
ah okay, I see what's going on.  There is an unnamed field in this workbook.  It's that feature that allows you to create temporary calculated fields on the shelves (in this case it's an LOD calc). So, when we are creating the mapping between fields and the sheets they are used in, we are processing the `<datasource-dependencies>` tag, we find the calculation that doesn't exist in the data source, only in the sheet's dependencies.

I'm not sure the best way to handle this situation.  We do not currently have a way of surfacing those types of fields with this version of the library.

My thought is to add a if the field is in the data source, do the normal thing.  If it doesn't skip it for now.  I'll open an additional issue to expose the sheet specific fields once we create the sheet object.

**Comment by t8y8** [comment]
That makes sense for now, the temp LOD calcs can be handled in a later release

**Comment by RussTheAerialist** [comment]
#59 fixes this.
