### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by t8y8** [tableau/document-api-python#61]
Opening an issue to track -- do we want to try and document the API reference in the README, in a dedicated docs folder, on some hosted site (readthedocs.org), or on the tableau developer site?

Right now we've got decent doc strings for most public functions and fairly clear function names -- but as it grows it'd be good to know where we want to take the docs.

**Comment by benlower** [comment]
@jdomingu ?

**Comment by jdomingu** [comment]
My vote would be to use the gh-pages branch model we've set up for the [WDC docs](http://tableau.github.io/webdataconnector/docs/). 

Do we have any reference material already created? Let me know when it would make sense for me to get involved in writing this up.

**Comment by t8y8** [comment]
@jdomingu reviving this.

There isn't anything (outside our samples) that I know of, right now we've got 3 main classes users will deal with but it might be time to doc the Workbook class as a starting point.

**Comment by t8y8** [comment]
I've been playing with lots of different things over the last few days, just going to throw my notes here.

- www.mkdocs.org
- http://www.sphinx-doc.org/en/1.4.8/
- https://mwop.net/blog/2016-01-29-automating-gh-pages.html

**Comment by t8y8** [comment]
This is addressed in #104 by enabling jekyll-generated docs for the site.

They are available at http://tableau.github.io/document-api-python.

I'm going to try and get the devguide up and ready soon -- and then we can start working on the docs themselves, but I think we can consider this issue closed.
