### ISSUE TITLE
"UnicodeDecodeError" when description has non-ascii characters

### ISSUE THREAD

**Issue by MiguelSR** [tableau/document-api-python#81]
When I try to load a workbook, if some of the fields has description with some kind of accents (like Ñ or á), it throws an UnicodeDecodeError.

I will provide now a PR that provides a solution for Python 2.

**Comment by MiguelSR** [comment]
This is the PR: https://github.com/tableau/document-api-python/pull/80

**Comment by MiguelSR** [comment]
I have my doubts about the comment "This is necessary for py3 support", actually. Should i move it to the line where `ET.tostring` is called?

By the way, if you find a more elegant way of fixing this please let me know.

Thanks.

**Comment by t8y8** [comment]
I left a quick review, just an alternative approach that I think should work.

Thank you for submitting the issue AND a PR so quickly :)

**Comment by RussTheAerialist** [comment]
#80 and #83 close this out.
