### ISSUE TITLE
Factor out Connections Class

### ISSUE THREAD

**Issue by benlower** [tableau/document-api-python#9]
Refactor things to clean this up

**Comment by benlower** [comment]
@t8y8 I think we factored out the connections, right? can this be closed?

**Comment by t8y8** [comment]
It could go further and have a BaseConnectionParser and then a FederatedConnectionParser and LegacyConnectionParser inherit from it, but I don't think it's worth the effort at the moment.

We can probably close this out until we need to touch that area again

**Comment by RussTheAerialist** [comment]
Based on @t8y8 's recommendation, closing.
