### ISSUE TITLE
Connecting to any data source throwing error - Attribute Error : Field object has no attribute 'description'

### ISSUE THREAD

**Issue by Jambes** [tableau/document-api-python#95]
I am trying to open a simple tds file  to check the field data type and count as it is in Sample Script but after the script print the total field and first field data type it is exiting with the error -

if field.description:
AttributeError: 'Field' object has no attribute 'description'

**Comment by t8y8** [comment]
@Jambes can you post the sample script or tds that you are using?

**Comment by t8y8** [comment]
@Jambes quick ping -- I'm still unable to reproduce this bug, can you help me reproduce the issue?

Thanks!

**Comment by t8y8** [comment]
@Jambes 

I'm going to close this issue because I haven't heard back -- please reopen it if it's still occurring after updating to the latest version!
