### ISSUE TITLE
Add port attribute to Connection object

### ISSUE THREAD

**Issue by geordielad** [tableau/document-api-python#96]
Can we add the port attribute to connection. This might be useful before the full document API is implemented. Some datasource changes could need to change the port in addition to the server etc. Some changes are a bit more involved but could include a port change. For example migrating from AWS RDS Postgres to Redshift might mean changing port from 5432 to 5439. A change of database variant could require other changes of course - schema in the relation for example.

**Comment by t8y8** [comment]
I've got a patch for this but I need to confirm the semantics of `port=''` vs no port attribute and when they're valid or not.

**Comment by t8y8** [comment]
@geordielad ask and ye shall receive. Enjoy!
